pattern_type: "chessboard"
pattern_cols: 8
pattern_rows: 6
center_distance_mm: 50

R_gimbal2imubody: [1, 0, 0, 0, 1, 0,  0, 0, 1]

camera_name: "hikrobot"
exposure_ms: 5
gain: 20
vid_pid: "2bdf:0001"

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

com_port: "/dev/ttyACM0"

# 重投影误差: 0.3361px
camera_matrix: [2388.1368055309649, 0, 722.4114163021228, 0, 2378.38210175937, 547.94232320034769, 0, 0, 1]
distort_coeffs: [-0.074270743390841804, 0.41587528228348647, 6.1425777372081354e-05, -0.00080799445926866707, 0]

